spring:
  application:
    name: SpringAi-Milvus

  ai:
    openai:
      base-url: https://api.siliconflow.cn/v1
      api-key: ${SILICONFLOW_API_KEY}
      embedding:
        model: BAAI/bge-large-zh-v1.5
        api-key: ${SILICONFLOW_API_KEY}
        base-url: https://api.siliconflow.cn/v1

    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530

app:
  vector-store:
    milvus:
      database-name: default
      embedding-dimension: 1024
      index-type: IVF_FLAT
      metric-type: COSINE
      initialize-schema: true
      collections:
        job: job_info
        resume: resume_info
        company: company_info

server:
  port: 8081
